version: '3.9'

# Services
services:

  # Database service
  surrealdb:
    container_name: surrealdb
    image: surrealdb/surrealdb:latest

    command: start --auth --log debug --user $DB_USER --pass $DB_PASSWORD memory

    ports:
      - $DB_PORT:8000