name: transformers_environment
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - torch==1.10.0
  - torchvision==0.11.1
  - cpuonly
  - cudatoolkit=none
  - pip
  - pip:
    - transformers==4.12.2
    - sentencepiece==0.1.96
    - tokenizers==0.10.3
    - sacremoses==0.0.46
    - packaging==21.1
    - requests==2.26.0
